### ISSUE TITLE
✨ [Client] 아파트 조회 페이지 - 우측 바 UI 생성

### ISSUE THREAD

**Issue by zer0who** [SSAFY-10-4-5-FINAL/pjt-final#1]
## 💬 Description
아파트 조회 페이지의 우측 바 컴포넌트를 만듭니다.

## 📝 Todo
- [x] 아파트 페이지 nav 생성
- [x] 우측 바 컴포넌트 틀 생성
- [x] 우측 바 컴포넌트의 검색 섹션 만들기
- [x] 단어가 포함된 검색 리스트 만들기
- [x] 추천 화면과 검색 결과 리스트 조회 화면에 들어갈 간략한 정보 화면 만들기
- [x] 추천 화면 만들기
- [x] 검색 결과 리스트 조회 화면 만들기
- [x] 자세한 조회 화면 만들기

## ETC
