### ISSUE TITLE
✨[Client] 메인 화면 UI 구현

### ISSUE THREAD

**Issue by zer0who** [SSAFY-10-4-5-FINAL/pjt-final#10]
## 💬 Description
메인 화면의 UI를 구현합니다.

## 📝 Todo
- [x] 메인화면 메인 바(Main center) UI
- [x] 메인화면 랜덤 아파트 소개 UI
- [x] 메인화면 공지사항 컴포넌트 UI
- [x] footer UI

## ETC
