### ISSUE TITLE
✨[Client] 게시판 UI

### ISSUE THREAD

**Issue by zer0who** [SSAFY-10-4-5-FINAL/pjt-final#12]
## 💬 Description
게시판(커뮤니티)의 UI를 만듭니다.

## 📝 Todo
- [x] 게시글 작성 화면
- [x] 게시글 리스트
- [x] 게시글 상세 화면
- [x] 게시글 수정 화면

## ETC
