### ISSUE TITLE
✨[Client] 아파트 페이지 API 연결

### ISSUE THREAD

**Issue by zer0who** [SSAFY-10-4-5-FINAL/pjt-final#23]
## 💬 Description
아파트 페이지의 API를 연결합니다.

## 📝 Todo
- [x] 검색창 입력 시 리스트 호출 API 연결(지역, 아파트)
- [x] 지역 기반 검색 시 아파트 리스트 호출 API 연결
- [x] 아파트명 기반 검색 시 아파트 리스트 호출 API 연결
- [x] 아파트 상세 조회 API 연결

## ETC
