### ISSUE TITLE
✨[Server] 아파트 탭 URL, API 만들기 

### ISSUE THREAD

**Issue by KangAeri** [SSAFY-10-4-5-FINAL/pjt-final#3]
## 💬 Description
아파트 정보 검색에 사용될 URL, API 를 만듭니다.

## 📝 Todo
- [x] 동코드로 아파트 리스트(아파트 상세정보, 거래내역은 제외) 가져오기
- [x] 아파트 코드로 아파트 상세정보 및 거래내역 객체 가져오기
- [x] 동 이름 일부로 지역정보 시군구, 읍면동, 동코드 등 동정보 리스트 가져오기
- [x] 아파트 이름 일부로 아파트 리스트(아파트 상세정보, 거래내역은 제외) 가져오기
- [x]  조회수 순 정렬된 아파트 10개 리스트 가져오기 : 컨트롤러까지구현/  apart테이블에 hit column 아직없음. 

## ETC
